# -*- coding: utf-8 -*-
"""FL 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oUgv7jiL3bBc2bsDd4jKqa-k31YpnXzY
"""

!pip install yfinance scikit-learn numpy pandas matplotlib torch

import numpy as np
import pandas as pd
import yfinance as yf
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import json, copy, warnings
warnings.filterwarnings("ignore")

import torch
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error

# Reproducibility
torch.manual_seed(42)
np.random.seed(42)

print("✅ All imports successful")
print(f"   PyTorch version : {torch.__version__}")
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"   Device          : {device}")

# ── Non-IID Setup ─────────────────────────────────────────────────────────────
# Each client has a DIFFERENT stock AND a different date range
# This mirrors real-world federated learning where data is never identical
CLIENT_CONFIG = {
    "Client 1": {"ticker": "AAPL", "start": "2020-01-01", "end": "2022-12-31", "color": "#2196F3"},
    "Client 2": {"ticker": "MSFT", "start": "2019-06-01", "end": "2022-06-30", "color": "#4CAF50"},
    "Client 3": {"ticker": "GOOGL","start": "2021-01-01", "end": "2023-12-31", "color": "#FF9800"},
    "Attacker": {"ticker": "AMZN", "start": "2020-01-01", "end": "2022-12-31", "color": "#F44336"},
}

SEQ_LEN    = 30   # 30 days of history to predict next day
BATCH_SIZE = 32
FEATURES   = ["Close", "Open", "High", "Low", "Volume"]

def add_technical_features(df):
    """Add multiple stock features for richer input."""
    df = df.copy()
    # Normalize volume
    df["Volume"] = df["Volume"] / df["Volume"].max()
    # Price-based features (returns)
    df["Close_ret"] = df["Close"].pct_change()
    df["High_ret"]  = df["High"].pct_change()
    df["Low_ret"]   = df["Low"].pct_change()
    df["Open_ret"]  = df["Open"].pct_change()
    df.dropna(inplace=True)
    return df

def make_sequences(df, seq_len=SEQ_LEN):
    """Convert time series into (X, y) sequences for LSTM."""
    feature_cols = ["Close_ret", "Open_ret", "High_ret", "Low_ret", "Volume"]
    data = df[feature_cols].values

    scaler = MinMaxScaler()
    data   = scaler.fit_transform(data)

    X, y = [], []
    for i in range(seq_len, len(data)):
        X.append(data[i - seq_len:i])       # shape: (seq_len, n_features)
        y.append(data[i, 0])                # predict next Close_ret

    X = np.array(X, dtype=np.float32)
    y = np.array(y, dtype=np.float32)

    # Train / Val / Test split: 70 / 15 / 15
    n       = len(X)
    t_end   = int(n * 0.70)
    v_end   = int(n * 0.85)

    return {
        "X_train": X[:t_end],   "y_train": y[:t_end],
        "X_val":   X[t_end:v_end], "y_val": y[t_end:v_end],
        "X_test":  X[v_end:],   "y_test":  y[v_end:],
        "scaler":  scaler,
        "raw_close": df["Close"].values[seq_len:]
    }

# ── Download and prepare data ─────────────────────────────────────────────────
print("Downloading stock data...")
client_data = {}

for name, cfg in CLIENT_CONFIG.items():
    df = yf.download(cfg["ticker"], start=cfg["start"],
                     end=cfg["end"], auto_adjust=True)
    df = df[["Close","Open","High","Low","Volume"]].dropna()
    df = add_technical_features(df)
    client_data[name] = make_sequences(df)
    d  = client_data[name]
    print(f"  {name} ({cfg['ticker']} {cfg['start']}→{cfg['end']}): "
          f"train={len(d['X_train'])} val={len(d['X_val'])} test={len(d['X_test'])}")

print("\n✅ Non-IID datasets ready — each client has different stock & timeframe")

class StockLSTM(nn.Module):
    """
    2-layer LSTM for stock return prediction.
    Input  : (batch, seq_len=30, n_features=5)
    Output : (batch, 1) — predicted next-day return
    """
    def __init__(self, input_size=5, hidden_size=64, num_layers=2, dropout=0.2):
        super().__init__()
        self.hidden_size = hidden_size
        self.num_layers  = num_layers

        self.lstm = nn.LSTM(
            input_size  = input_size,
            hidden_size = hidden_size,
            num_layers  = num_layers,
            batch_first = True,
            dropout     = dropout
        )
        self.fc = nn.Sequential(
            nn.Linear(hidden_size, 32),
            nn.ReLU(),
            nn.Dropout(0.1),
            nn.Linear(32, 1)
        )

    def forward(self, x):
        h0 = torch.zeros(self.num_layers, x.size(0), self.hidden_size).to(x.device)
        c0 = torch.zeros(self.num_layers, x.size(0), self.hidden_size).to(x.device)
        out, _ = self.lstm(x, (h0, c0))
        out     = out[:, -1, :]   # take last timestep
        return self.fc(out).squeeze(-1)

def get_dataloader(X, y, batch_size=BATCH_SIZE, shuffle=True):
    ds = TensorDataset(torch.tensor(X), torch.tensor(y))
    return DataLoader(ds, batch_size=batch_size, shuffle=shuffle)

def get_model():
    return StockLSTM(input_size=5, hidden_size=64, num_layers=2).to(device)

# Test model shape
m   = get_model()
inp = torch.randn(8, SEQ_LEN, 5).to(device)
out = m(inp)
print(f"✅ LSTM model defined")
print(f"   Input  : (batch=8, seq_len={SEQ_LEN}, features=5)")
print(f"   Output : {out.shape}")
print(f"   Params : {sum(p.numel() for p in m.parameters()):,}")

def train_local(global_weights, X_train, y_train, epochs=3, lr=0.001):
    """
    Train a local LSTM on client data.
    Returns updated model weights (never shares raw data).
    """
    model = get_model()
    model.load_state_dict(copy.deepcopy(global_weights))
    model.train()

    optimizer = torch.optim.Adam(model.parameters(), lr=lr)
    criterion = nn.MSELoss()
    loader    = get_dataloader(X_train, y_train)

    epoch_losses = []
    for epoch in range(epochs):
        total_loss = 0
        for X_batch, y_batch in loader:
            X_batch = X_batch.to(device)
            y_batch = y_batch.to(device)
            optimizer.zero_grad()
            pred = model(X_batch)
            loss = criterion(pred, y_batch)
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimizer.step()
            total_loss += loss.item()
        epoch_losses.append(total_loss / len(loader))

    return model.state_dict(), epoch_losses

def proof_of_learning(weights, X_val, y_val, epsilon=1e-6):
    """
    Evaluate model on global validation set
    Returns quality score (0-100)
    """
    model = get_model()
    model.load_state_dict(weights)
    model.eval()

    loader = get_dataloader(X_val, y_val, shuffle=False)
    preds, targets = [], []

    with torch.no_grad():
        for X_batch, y_batch in loader:
            p = model(X_batch.to(device)).cpu().numpy()
            preds.extend(p)
            targets.extend(y_batch.numpy())

    mse = mean_squared_error(targets, preds)
    return mse, 1.0 / (mse + epsilon)

def federated_average(weight_list, alpha_list):
    """
    Weighted FedAvg
    alpha_list: softmax governance weights
    """
    avg_weights = copy.deepcopy(weight_list[0])
    for key in avg_weights:
        avg_weights[key] = torch.zeros_like(avg_weights[key], dtype=torch.float32)
        for weights, alpha in zip(weight_list, alpha_list):
            avg_weights[key] += alpha * weights[key].float()
    return avg_weights

def softmax_weights(scores):
    """Equation (4) from the paper."""
    scores = np.array(scores, dtype=float)
    e      = np.exp(scores - np.max(scores))
    return e / e.sum()

def normalize_scores(raw_scores, threshold=10):
    """Normalize raw quality scores to 0-100 for the blockchain."""
    arr     = np.array(raw_scores)
    min_s   = arr.min()
    max_s   = arr.max()
    normed  = ((arr - min_s) / (max_s - min_s + 1e-9)) * 100
    return [max(0, int(s)) for s in normed]

print("✅ FL functions defined")

NUM_ROUNDS      = 5
SCORE_THRESHOLD = 10
CLIENTS         = ["Client 1", "Client 2", "Client 3"]
ALL_LABELS      = ["Client 1", "Client 2", "Client 3", "Attacker"]

# Global validation set — use Client 1's val set as the held-out DAO validator
X_global_val = client_data["Client 1"]["X_val"]
y_global_val = client_data["Client 1"]["y_val"]

# Initialize global model
global_model = get_model()
global_weights = global_model.state_dict()

# Tracking metrics
history = {
    "round_mse":         [],   # global model MSE per round
    "client_scores":     {c: [] for c in ALL_LABELS},
    "client_train_loss": {c: [] for c in CLIENTS},
    "normalized_scores": [],
}

print("=" * 60)
print("  FEDERATED LEARNING — LSTM STOCK PREDICTION")
print(f"  {NUM_ROUNDS} rounds | Non-IID data | 3 honest + 1 attacker")
print("=" * 60)

for round_num in range(1, NUM_ROUNDS + 1):
    print(f"\n📡 Round {round_num}/{NUM_ROUNDS}")
    print("-" * 45)

    local_weights_list = []
    raw_scores         = []
    round_mses         = []

    for label in ALL_LABELS:
        data = client_data[label]

        if label == "Attacker":
            # Model poisoning: train normally then inject Gaussian noise
            weights, losses = train_local(
                global_weights,
                data["X_train"], data["y_train"]
            )
            for key in weights:
                weights[key] = weights[key] + torch.randn_like(weights[key]) * 2.0
            print(f"  ☠  {label} (AMZN): injecting noise into weights")
        else:
            weights, losses = train_local(
                global_weights,
                data["X_train"], data["y_train"]
            )
            history["client_train_loss"][label].append(np.mean(losses))

        # Proof of Learning — evaluate on global val set
        mse, raw_score = proof_of_learning(weights, X_global_val, y_global_val)
        raw_scores.append(raw_score)
        round_mses.append(mse)
        local_weights_list.append(weights)

        if label != "Attacker":
            print(f"  ✅ {label} ({CLIENT_CONFIG[label]['ticker']}): "
                  f"train_loss={np.mean(losses):.6f} | val_mse={mse:.6f}")
        else:
            print(f"  ❌ {label}: val_mse={mse:.6f} (poisoned — high error expected)")

    # Normalize to 0-100 for blockchain
    norm_scores = normalize_scores(raw_scores)
    history["normalized_scores"].append(dict(zip(ALL_LABELS, norm_scores)))

    for label, ns, rs in zip(ALL_LABELS, norm_scores, raw_scores):
        history["client_scores"][label].append(ns)

    print(f"\n  Normalized scores → blockchain:")
    for label, score in zip(ALL_LABELS, norm_scores):
        flag = "← REJECTED" if score < SCORE_THRESHOLD else ""
        print(f"     {label}: {score}/100  {flag}")

    # FedAvg — only aggregate qualifying honest clients
    qualifying_w = []
    qualifying_s = []
    for w, s, sc in zip(local_weights_list, raw_scores, norm_scores):
        if sc >= SCORE_THRESHOLD:
            qualifying_w.append(w)
            qualifying_s.append(s)

    alpha        = softmax_weights(qualifying_s)
    global_weights = federated_average(qualifying_w, alpha)

    # Evaluate new global model
    global_mse, _ = proof_of_learning(global_weights, X_global_val, y_global_val)
    history["round_mse"].append(global_mse)
    print(f"\n  🌐 Global model MSE after round {round_num}: {global_mse:.8f}")

print("\n" + "=" * 60)
print("  FL SIMULATION COMPLETE")
print("=" * 60)

import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import numpy as np
from IPython.display import FileLink # For downloading in notebooks

# ── 1. GLOBAL HIGH-QUALITY SETTINGS ──────────────────────────────────────────
plt.rcParams.update({
    'figure.facecolor': 'white',
    'axes.facecolor': 'white',
    'font.family': 'sans-serif',
    'font.size': 14,
    'axes.labelweight': 'bold',
    'axes.titlesize': 18,
    'axes.titlepad': 20,
    'legend.frameon': True,
    'legend.fontsize': 12,
    'xtick.direction': 'out',
    'ytick.direction': 'out',
    'grid.color': '#E6E6E6',
    'grid.linestyle': '--'
})

def generate_and_save_plot():
    # Increase figure size for high-res output
    fig = plt.figure(figsize=(22, 18), dpi=300)
    fig.suptitle("F-DAO: Federated LSTM Stock Prediction Results", fontsize=24, fontweight="bold", y=0.98)
    gs = gridspec.GridSpec(3, 2, figure=fig, hspace=0.45, wspace=0.3)

    rounds_x = list(range(1, NUM_ROUNDS + 1))
    colors = {k: v["color"] for k, v in CLIENT_CONFIG.items()}

    # ── Plot 1: Global Model MSE (Fixed Headroom) ─────────────────────────────
    ax1 = fig.add_subplot(gs[0, 0])
    ax1.plot(rounds_x, history["round_mse"], "o-", color="#8E24AA", lw=3, ms=10, zorder=3)
    ax1.fill_between(rounds_x, history["round_mse"], alpha=0.1, color="#8E24AA")

    # FIX: Increase Y-limit by 30% to prevent title overlap
    ymin, ymax = min(history["round_mse"]), max(history["round_mse"])
    ax1.set_ylim(ymin * 0.95, ymax * 1.3)

    ax1.set_title("Global Model Convergence", fontweight="bold")
    ax1.set_ylabel("Validation MSE")
    ax1.grid(True)

    for i, v in enumerate(history["round_mse"]):
        ax1.annotate(f"{v:.5f}", (rounds_x[i], v), textcoords="offset points",
                     xytext=(0, 15), ha="center", fontsize=11, fontweight="bold",
                     bbox=dict(boxstyle='round,pad=0.2', fc='white', ec='#8E24AA', alpha=0.7))

    # ── Plot 2: Client Train Loss ──────────────────────────────────────────────
    ax2 = fig.add_subplot(gs[0, 1])
    for label in CLIENTS:
        ax2.plot(rounds_x, history["client_train_loss"][label], "o-",
                 label=label, color=colors[label], lw=2.5, ms=8)
    ax2.set_title("Individual Client Loss Curves", fontweight="bold")
    ax2.set_ylabel("MSE Loss")
    ax2.legend(loc='upper right')
    ax2.grid(True)

    # ── Plot 3: Contribution Scores (Shifted Legend) ──────────────────────────
    ax3 = fig.add_subplot(gs[1, 0])
    x = np.arange(NUM_ROUNDS)
    w = 0.18
    offsets = [-1.5, -0.5, 0.5, 1.5]
    for i, label in enumerate(ALL_LABELS):
        ax3.bar(x + offsets[i] * w, history["client_scores"][label], w,
                label=label, color=colors[label], edgecolor='white', alpha=0.9)

    ax3.axhline(y=SCORE_THRESHOLD, color="#D32F2F", ls="--", lw=2, label="Threshold")
    ax3.set_title("Reputation Scores per Round", fontweight="bold")
    ax3.set_xticks(x)
    ax3.set_xticklabels([f"Round {i}" for i in rounds_x])
    ax3.set_ylabel("Quality Score")
    ax3.legend(loc='upper left', bbox_to_anchor=(1, 1)) # Moved outside to avoid overlap
    ax3.grid(True, axis='y')

    # ── Plot 4: Token Distribution (High-Visibility Labels) ───────────────────
    ax4 = fig.add_subplot(gs[1, 1])
    final_scores = [sum(history["client_scores"][l]) for l in ALL_LABELS]
    total = sum(final_scores)
    pcts = [s / total * 100 if total > 0 else 0 for s in final_scores]
    bars = ax4.bar(ALL_LABELS, pcts, color=[colors[l] for l in ALL_LABELS], edgecolor="black", lw=0.5)
    ax4.set_title("Final Governance Power Share", fontweight="bold")
    ax4.set_ylabel("Tokens (%)")
    ax4.set_ylim(0, max(pcts) + 15)

    for bar in bars:
        height = bar.get_height()
        ax4.text(bar.get_x() + bar.get_width()/2., height + 2,
                 f'{height:.1f}%', ha='center', va='bottom', fontweight='bold', fontsize=14)

    # ── Plot 5: Final Predictions (Cleaned Up) ────────────────────────────────
    ax5 = fig.add_subplot(gs[2, :])
    ax5.plot(actuals, label="Actual Returns", color="#1976D2", lw=2, alpha=0.8)
    ax5.plot(preds, label="LSTM Prediction", color="#F4511E", lw=2, ls="--")
    ax5.set_title(f"Market Prediction Accuracy (MSE: {test_mse:.6f})", fontweight="bold")
    ax5.set_xlabel("Test Time Steps")
    ax5.legend(loc='upper right', framealpha=0.9)
    ax5.grid(True, alpha=0.3)

    # ── 2. SAVE AND DOWNLOAD ──────────────────────────────────────────────────
    filename = "FDAO_HighRes_Results.png"
    plt.savefig(filename, dpi=300, bbox_inches="tight")
    plt.show()

    print(f"✅ High-quality plot saved as {filename}")
    return filename

# Run the function
output_file = generate_and_save_plot()

# This generates a clickable download link in Jupyter/Colab
FileLink(output_file)

import json

ALL_LABELS = ["Client 1", "Client 2", "Client 3", "Attacker"]
NUM_ROUNDS = 5

fl_output = {
    "rounds": [
        {
            "round":        r + 1,
            "participants": ALL_LABELS,
            "scores":       [history["client_scores"][l][r] for l in ALL_LABELS],
            "global_mse":   history["round_mse"][r]
        }
        for r in range(NUM_ROUNDS)
    ],
    "final_scores": [history["client_scores"][l][-1] for l in ALL_LABELS],
    "participants":  ALL_LABELS,
    "addresses": {
        "Client 1": "0x70997970C51812dc3A010C7d01b50e0d17dc79C8",
        "Client 2": "0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC",
        "Client 3": "0x90F79bf6EB2c4f870365E785982E1f101E93b906",
        "Attacker": "0x15d34AAf54267DB7D7c367839AAf71A00a2C6A65"
    }
}

with open("fl_results.json", "w") as f:
    json.dump(fl_output, f, indent=2)

print("✅ Saved! Contents:")
print(json.dumps(fl_output, indent=2))

from google.colab import files
files.download("fl_results.json")
files.download("fdao_results.png")